### PR TITLE
Friendship/v1

### PR DESCRIPTION
**Pull request by DeliceLydia**
Description

In this project, I have implemented a social media app That allows users to create an account, creates a post, comment on a post, like a post, send and receive friend requests

Model Relations

- User can create many posts

- User can have many friends

- User can have many likes

- Post can have many comments

- Post can have many likes

- Post belongs to a user

### CODE REVIEW

**Comment by mimipeshy** [comment]
#### STATUS : CHANGES REQUIRED :red_circle: :recycle: 

Hey team @DeliceLydia :wave: :wave: great job on working on this project. However, I will note a few changes that need to be changed :arrow_down: 

- [ ] I was unable to run your migrations and it's because you were trying to change a column name from status to confirmed. This is from fix_column_name. This column **status** does not exist in the friendship column but **confirmed** does exist. Kindly check if you meant to change from confirmed to status.
image

- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). This means, a user should only see posts from confirmed friends. Currently, a user sees all posts from all users. Fix this.


That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, I will be glad to help_
Regards
Peris Ndanu

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello Team, good job working on this milestone. However, there are still some changes to do before moving on to the next.

<hr>

- [ ] The inviting, accepting, and rejecting methods are working fine, but when I request a friendship, I immediately can see their posts before they accept, kindly fix that!
- [ ] When I create a new user, it's duplicating in the All Users page (see image below)
Screenshot

- [ ] Please create a .gitignore file and add the ```node_modules/``` folder to it, the folder is too large!

<hr>

Kindly do the changes and ask for another re-review.
Good luck and happy coding 👨‍💻💻

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [ ] You have a number of spelling and grammar errors in Readme. Please work on them. You can use [Grammarly](https://app.grammarly.com/) for this purpose. 
- [ ] As requested by previous TSEs to add extra files/folders to .gitignore. Please add.VSCODE to it. 


**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @DeliceLydia 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Please add the `.gitgnore` file and add .VSCODE to it.
- [ ] Please Add the License in the README file or remove this heading
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @DeliceLydia**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
